name: Deploy to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
        chmod 400 ec2_key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ${{ secrets.EC2_APP_DIR }}
          git pull origin main
          npm install
          pm2 restart devshop || pm2 start app.js --name devshop
        EOF
